name: .NET 6 CI/CD

on:
  push:
    branches:
      - develop
    tags:
      - v*
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
jobs:
  build:
    strategy:
      matrix:
        framework: [ 'net6.0' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build Debug
      run: dotnet build GB28181.Server/GB28181.Server.csproj --framework  ${{ matrix.framework }} -c Debug
    - name: Build Release
      run: dotnet build GB28181.Server/GB28181.Server.csproj --framework  ${{ matrix.framework }} -c Release 
