name: .NET 6 CI/CD

on:
  push:
    branches:
      - develop
    tags:
      - v*
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
jobs:
  build:
    runs-on: windows-2022
    name: dotnet windows GB28181
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore GB28181.Solution.sln
    - name: Build Release Debug
      run: dotnet build -c Debug GB28181.Solution.sln --no-restore
    - name: Build Solution Release
      run: dotnet build -c Release GB28181.Solution.sln --no-restore
